billing/config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  patch '/close_billing_cycle_and_open_new' => 'dashboard#close_billing_cycle_and_open_new'

  namespace :employee do
    get '/dashboard' => 'dashboard#index'
  end

  get '/login' => 'auth/oauth_sessions#new'
  get '/auth/:provider/callback' => 'auth/oauth_sessions#create'
  delete '/logout' => 'auth/oauth_sessions#destroy'
end

billing/app/models/account.rb
class Account < ApplicationRecord
  has_many :transactions, dependent: :destroy
  has_one :balance, dependent: :destroy
  has_many :tasks, dependent: :destroy

  enum role: {
    admin: 'admin',
    manager: 'manager',
    employee: 'employee',
    accountant: 'accountant'
  }
end

billing/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

billing/app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :account
end

billing/app/models/billing_cycle.rb
class BillingCycle < ApplicationRecord
  has_many :transactions, dependent: :destroy

  enum status: {
    open: 'open',
    closed: 'closed'
  }

  def self.current
    open.last
  end
end

billing/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :account

  before_create do
    self.amount = rand(10..20)
    self.fee = rand(20..40)
  end
end

billing/app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :billing_cycle

  enum kind: {
    enrollment: 'enrollment',
    withdrawal: 'withdrawal',
    payment: 'payment'
  }

  after_create do
    balance = account.balance

    balance.amount += debit
    balance.amount -= credit

    balance.save!

    self.reload

    ProduceEvent.call(
      event_name: Events::TRANSACTION_APPLIED,
      event_version: 1,
      schema: 'billing.transaction_applied',
      topic: KafkaTopics::TRANSACTIONS_APPLIED,
      data: {
        public_id: public_id,
        owner_public_id: account.public_id,
        debit: debit,
        credit: credit,
        description: description,
        kind: kind
      }
    )
  end
end

billing/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_account!
    redirect_to login_path unless current_account
  end

  def current_account
    return if session[:account_id].blank?

    @current_account ||= Account.find_by(id: session[:account_id])
  end

  def account_signed_in?
    current_account.present?
  end

  helper_method :account_signed_in?, :current_account
end

billing/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_account!
  before_action :authorize!

  def index
    @withdrawal_amount = BillingCycle.current.transactions.withdrawal.sum(:credit)
    @enrollment_amount = BillingCycle.current.transactions.enrollment.sum(:debit)

    @top_managers_income =  -(@withdrawal_amount + @enrollment_amount)
  end

  def close_billing_cycle_and_open_new
    @payment_transactions = []
    BillingCycle.transaction do
      Account.employee.includes(:balance).each do |account|
        next if account.balance.amount <= 0

        @payment_transactions << account.transactions.payment.create!(
          credit: account.balance.amount,
          debit: 0,
          billing_cycle: BillingCycle.current
        )
      end

      BillingCycle.current.update!(status: 'closed')

      BillingCycle.create!
    end

    @payment_transactions.each do |transaction|
      puts "Send payment amount #{transaction.amount} to email #{transaction.account.email}"

      event = {
        event_name: Events::EMPLOYEE_PAYMENT_MADE,
        data: {
          employee_public_id: transaction.account.public_id,
          debit: transaction.debit,
          credit: transaction.credit,
          payment_at: transaction.created_at
        }
      }

      WaterDrop::SyncProducer.call(event.to_json, topic: KafkaTopics::EMPLOYEE_PAYMENTS)
    end

    redirect_to root_path, notice: 'Billing cycle successfully closed and new opened.'
  end

  private

  def authorize!
    return if current_account.admin? || current_account.accountant?

    return redirect_to employee_dashboard_path if current_account.employee?

    redirect_to login_path
  end
end

billing/app/controllers/employee/dashboard_controller.rb
module Employee
  class DashboardController < ApplicationController
    before_action :authenticate_account!
    before_action :authorize!

    def index
      @transactions = current_account.transactions.order(id: :desc)
    end

    private

    def authorize!
      return if current_account.employee?

      return redirect_to root_path if current_account.admin? || current_account.accountant?

      redirect_to login_path
    end
  end
end

billing/app/helpers/application_helper.rb
module ApplicationHelper
end

billing/app/views/dashboard/index.slim
= link_to 'Close billing cycle and open new', close_billing_cycle_and_open_new_path, class: 'btn btn-primary', data: { turbo_method: "patch" }

h4.mt-5
  | Top Managers Income: #{@top_managers_income}

billing/app/views/employee/dashboard/index.slim
h4
  | Current balance: #{current_account.balance.amount}

h4 Transaction log:

table.table
  tr
    th
      | Created at
    th
      | Type
    th
      | Debit
    th
      | Credit
    th
      | Description
  - @transactions.each do |transaction|
    tr
      td = transaction.created_at
      td = transaction.kind
      td
        = transaction.debit
      td
        = transaction.credit
      td
        = transaction.description

billing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <% if account_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Billing</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="<%#= root_path %>">Dashboard</a>
                </li>
              </ul>
            </div>
            <span><%= current_account.email %></span>
            <%= link_to 'Выйти', logout_path, class: 'btn btn-default', data: { turbo_method: "delete" } %>
          </div>
        </nav>
      <% end %>
      <p><%= notice %></p>
      <%= yield %>
    </div>
  </body>
</html>