task_tracker/config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :tasks, only: %i[new create edit update] do
    patch :shuffle, on: :collection
  end

  namespace :employee do
    resources :tasks, only: %i[index] do
      patch :complete, on: :member
    end
  end

  get '/login' => 'auth/oauth_sessions#new'
  get '/auth/:provider/callback' => 'auth/oauth_sessions#create'
  delete '/logout' => 'auth/oauth_sessions#destroy'
end

task_tracker/app/models/account.rb
class Account < ApplicationRecord
  has_many :tasks, dependent: :destroy

  enum role: {
    admin: 'admin',
    manager: 'manager',
    employee: 'employee',
    accountant: 'accountant'
  }
end

task_tracker/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :account

  enum status: {
    open: 'open',
    completed: 'completed'
  }

  validates :description, presence: true

  validate :jira_id_not_in_title

  def jira_id_not_in_title
    return if !title.match(/[\[\]]/)

    errors.add(:title, 'contains jira_id')
  end
end

task_tracker/app/controllers/employee/tasks_controller.rb
module Employee
  class TasksController < ApplicationController
    before_action :authenticate_account!

    def index
      @tasks = current_account.tasks.order(id: :desc)
    end

    def complete
      @task = Task.open.find_by(id: params[:id])
      return head 404 if @task.blank?
      #return head 403 if @task.account != current_account
      return head 400 if @task.completed?

      @task.update(status: :completed, completed_at: Time.current)

      # Buisiness event

      ProduceEvent.call(
        event_name: Events::TASK_COMPLETED,
        event_version: 1,
        schema: 'task_tracker.task_completed',
        topic: KafkaTopics::TASK_LIFECYCLE,
        data: {
          public_id: @task.public_id,
          performer_public_id: @task.account.public_id,
          description: @task.description,
          completed_at: @task.completed_at.to_s
        }
      )

      redirect_to employee_tasks_path, notice: 'Task successfully completed.'
    end
  end
end

task_tracker/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_account!
  before_action :set_task, only: %i[edit update]

  def index
    @tasks = Task.all.includes(:account).order(id: :desc)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.account = employee_accounts.sample
    if @task.save
      @task.reload

      # CUD event
      ProduceEvent.call(
        event_name: Events::TASK_CREATED,
        event_version: 1,
        schema: 'task_tracker.task_created',
        topic: KafkaTopics::TASKS_STREAM,
        data: {
          public_id: @task.public_id,
          title: @task.title,
          jira_id: @task.jira_id,
          description: @task.description,
          performer_public_id: @task.account.public_id,
          status: @task.status
        }
      )

      # Buisiness event
      ProduceEvent.call(
        event_name: Events::TASK_ADDED,
        event_version: 1,
        schema: 'task_tracker.task_added',
        topic: KafkaTopics::TASK_LIFECYCLE,
        data: {
          public_id: @task.public_id,
          title: @task.title,
          jira_id: @task.jira_id,
          description: @task.description,
          performer_public_id: @task.account.public_id,
          status: @task.status
        }
      )

      # Buisiness event
      ProduceEvent.call(
        event_name: Events::TASK_ASSIGNED,
        event_version: 1,
        schema: 'task_tracker.task_assigned',
        topic: KafkaTopics::TASK_LIFECYCLE,
        data: {
          public_id: @task.public_id,
          performer_public_id: @task.account.public_id,
          description: @task.description
        }
      )

      redirect_to root_path, notice: 'Task successfully added.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      # CUD event
      ProduceEvent.call(
        event_name: Events::TASK_UPDATED,
        event_version: 1,
        schema: 'task_tracker.task_updated',
        topic: KafkaTopics::TASKS_STREAM,
        data: {
          public_id: @task.public_id,
          title: @task.title,
          jira_id: @task.jira_id,
          description: @task.description,
          performer_public_id: @task.account.public_id,
          status: @task.status,
          completed_at: @task.completed_at
        }
      )
      redirect_to root_path, notice: 'Task successfully updated.'
    else
      render :edit
    end
  end

  def shuffle
    @open_tasks = Task.open

    @open_tasks.each do |task|
      task.update(account: employee_accounts.sample)

      # Buisiness event
      ProduceEvent.call(
        event_name: Events::TASK_ASSIGNED,
        event_version: 1,
        schema: 'task_tracker.task_assigned',
        topic: KafkaTopics::TASK_LIFECYCLE,
        data: {
          public_id: task.public_id,
          performer_public_id: task.account.public_id,
          description: task.description
        }
      )
    end

    redirect_to root_path, notice: 'Tasks successfully assigned.'
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :jira_id)
  end

  def employee_accounts
    @employee_accounts ||= Account.employee
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

task_tracker/app/views/employee/tasks/index.slim
table.table
  tr
    th #
    th Описание
    th Статус
    td
  - @tasks.each do |task|
    tr
      td = task.id
      td = task.description
      td = task.status
      td
        - if task.open?
          = link_to 'Завершить', complete_employee_task_path(task),  data: { turbo_method: "patch" }

task_tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <% if account_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Task Tracker</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="<%= root_path %>">Все задачи</a>
                </li>
                <% if current_account.employee? %>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="<%= employee_tasks_path %>">Мои задачи</a>
                  </li>
                <% end %>
              </ul>
            </div>
            <span><%= current_account.email %></span>
            <%= link_to 'Выйти', logout_path, class: 'btn btn-default', data: { turbo_method: "delete" } %>
          </div>
        </nav>
      <% end %>
      <p><%= notice %></p>
      <%= yield %>
    </div>
  </body>
</html>

task_tracker/app/views/tasks/_form.slim
= form_with(model: @task, local: true, html: {'data-turbo' => 'false'}) do |f|
  - if @task.errors.any?
    #error_explanation
      h2 #{pluralize(@task.errors.count, "error")} prohibited this task from being saved:

      ul
        - @task.errors.full_messages.each do |message|
          li = message
  div
    = f.label :title
  div
    = f.text_field(:title)

  div
    = f.label :jira_id
  div
    = f.text_field(:jira_id)

  div
    = f.label :description
  div
    = f.text_area(:description)

  .actions
    = f.submit

task_tracker/app/views/tasks/edit.slim
h1 Edit task

= render 'form'

task_tracker/app/views/tasks/index.slim
= link_to 'Добавить задачу', new_task_path
br
= link_to 'Заассайнить задачи', shuffle_tasks_path, data: { turbo_method: "patch" }
table.table
  tr
    th #
    th Описание
    th Статус
    th Исполнитель
    td
  - @tasks.each do |task|
    tr
      td = task.id
      td = task.description
      td = task.status
      td = task.account.full_name
      td
        - if task.open?
          = link_to 'Завершить', complete_employee_task_path(task),  data: { turbo_method: "patch" }
        '
        = link_to 'Изменить', edit_task_path(task)

task_tracker/app/views/tasks/new.slim
h1 Add task

= render 'form'